# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          npm ci

      # 4. Run TypeScript type checking
      - name: TypeScript Type Check
        run: npx tsc --noEmit
        # Ensure your project has a "tsconfig.json"

      # 5. Run Linting
      - name: Lint Code
        run: npm run lint

      #Â 6. Run format check
      - name: Check Code Formatting
        run: npm run format:check

      # 7. Run Tests
      - name: Run Tests
        run: npm run test:ci

      # 8. Upload Test Coverage Report (Optional)
      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

  functions:
    name: Functions Build and Lint
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install functions dependencies
      - name: Install dependencies
        run: |
          cd functions
          npm ci

      # 4. Lint functions folder
      - name: Lint
        run: |
          cd functions
          npm run lint

      # 5. Build functions
      - name: Build
        run: |
          cd functions
          npm run build
